# Векторы. Основные понятия

Определение: Вектор — это набор чисел, записанных в определённом порядке (в столбик или в строчку).

На рынке новостроек появилось предложение от застройщика "Гарантия" — двухкомнатная квартира общей площадью 59.5 кв.м, жилой площадью 31.4 кв.м на 19-м этаже 22-х этажного дома. В доме 2 подъезда. Цена за квадратный метр квартиры у этого застройщика составляет 60550 рублей.
Признаков может быть сколько угодно много. Таким образом, мы можем описать нашу квартиру числовой последовательностью важных для нас признаков при покупке квартиры: 

In [52]:
import numpy as np
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

В NumPy вектор и массив - одно и то же. 
Исключение - понятие вектор-столбец и вектор-строка - фактически двумерные массивы, 
где один из атрибутов shape равен 1.

In [53]:
print("ndim:", apartment.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 1
shape: (6,)


In [54]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]
share_living_space

0.5277310924369748

Избавимся от старых признаков, посредством функции delete(), которую предоставляет библиотека numpy. Передадим в значение функции индексы признаков, которые необходимо удалить из нашего массива apartment:

In [55]:
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)

In [56]:
len(apartment)

5

Пусть дан вектор в python вида t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13]), содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно.

In [57]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
t[4]
    

24

Найдите сумму и разность вектров 

In [58]:
x = np.array([5, 2])
y = np.array([-5, -11])
x - y

array([10, 13])

Доходы Алексея за три месяца составили 120, 150, 90, и тысяч рублей, его жены: 130, 130, и 130 тысяч рублей, а тёщи: 2, 3, и  2.5 тысячи евро.

Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля

In [59]:
mother_in_law = np.array([2, 3, 2.5]) * 72
mother_in_law

array([144., 216., 180.])

Найдите вектор суммарного дохода семьи в тыс. рублей по месяцам

In [60]:
alex = np.array([120, 150, 90])
wife = np.array([130, 130, 130])

mother_in_law + alex + wife

array([394., 496., 400.])

Найдите линейную комбинацию векторов 

In [61]:
x = np.array([4, 5])
y = np.array([2, 1])
u = np.array([1, 0])

xc = 2
yc = -3
uc = 5

x * xc + y * yc + uc * u


array([7, 7])

Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.

На изготовление одной ракеты он тратит 200 рублей, а продаёт их по 400 рублей за штуку.

Найдите вектор прибыли Вовочки за эти 4 недели.

In [62]:
made = np.array([3,4,5,9])
sale = np.array([1,5,3,6])

value = 200
cost = 400

sale * cost - made * value


array([-200, 1200,  200,  600])

# Скалярное произведение векторов

Найдите скалярное произведение векторов

In [63]:
x = np.array([4,5,-1])
y = np.array([2,0,1])

np.dot(x, y)

7

Вычислите длину вектора

In [64]:
x = np.array([4, 6, 1])

def getLen(array):
    sum = 0
    for i in array:
        sum += i**2
    return sum ** 0.5

getLen(x)

7.280109889280518

В Hut_Paradise_DF представлен фрагмент базы данных агенства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [65]:
import pandas as pd
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

Найдите вектор параметров квартиры номер 5

In [66]:
Hut_Paradise_DF.values[:][4]

array([40, 33,  1,  6, 20, 16])

Найдите вектор этажей всех квартир:

In [67]:
Hut_Paradise_DF['4.Floor'].values

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [68]:
Hut_Paradise_DF.values[2][3]

10

Найдите количество квартир

In [69]:
len(Hut_Paradise_DF.values)

9

Вычислите вектор нежилой площади

In [70]:
(Hut_Paradise_DF['2.Area'] - Hut_Paradise_DF['6.Liv.Area']).values

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [71]:
ua_g = 4 / 10

(Hut_Paradise_DF['1.Rent'] * ua_g).values



array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут. Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели:

In [72]:
time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
(Hut_Paradise_DF['5.Demo two weeks'].values * time).sum()

1348

In [73]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3

In [74]:
result = v * 2 + -3 * w
result

array([-3, 14,  3,  4,  2])

In [75]:
np.dot(result, u)

0

Нормируйте векторы

In [76]:
def vectorLenght(vector):
    result = 0
    for i in vector:
        result += i**2
    return result ** 0.5

def invLenght(lenght):
    return 1 / lenght


u_normal = u * invLenght(vectorLenght(u))
v_normal = v * invLenght(vectorLenght(v))
w_normal = w * invLenght(vectorLenght(w))

print(round(u_normal[2], 3))
print(round(v_normal[3], 3))
print(round(w_normal[0], 3))

0.289
0.667
0.213


# Матрицы

Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы NumPy

In [77]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы.

In [78]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
Inc.diagonal()

array([100, 200, 100])

Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.

In [79]:
Cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption])
np.diag(Cons[:, ::-1])

array([ 60,  80, 100])

Доходы представлены до уплаты налогов. Налоговая ставка - 13%. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

In [80]:
fee = Inc * 0.13
real_inc = (Inc - fee)
real_inc.T[0]

array([ 87. , 130.5,  78.3])

Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами и расходами)

In [81]:
(real_inc - Cons).T

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

Даны матрица A и вектор x

In [82]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

Найдите произведение матрицы и вектора в том порядке, в котором их можно умножить.

In [83]:
A@x

array([26, 30])

In [84]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

(B@A)[0][3]

14

In [85]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

a = np.array([x, y, z])
aT = np.array([x, y, z]).T

a@aT

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [86]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

Найдите вектор выручки Бориса.

In [87]:
count = Count_DF.iloc()[1].values

price = Price_DF.iloc[1].values

count * price 

array([ 3.6, 52.5,  3. , 25. ,  6. ])

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [88]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
((Count_DF * Price_DF)@com).values

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

Найдите вектор прибыли стилистов.

In [89]:
((Count_DF * Price_DF)@(np.ones(5)-com)).values

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

# Обратная матрица

In [90]:
matrix = np.matrix([[1,2], [2, 5]])

np.linalg.inv(matrix)

matrix([[ 5., -2.],
        [-2.,  1.]])

# Определитель матрицы

In [91]:
A = np.array([[1,2], [1,1]])
B = np.array([[5, -2], [-1, 4]])

np.linalg.det(A + B)

29.99999999999999

In [92]:
A = np.array([[2, 0, 0], [0, 1, 0], [0, 0, 4]])
Ainv = np.linalg.inv(A)
np.linalg.det(A)
np.linalg.det(Ainv)

0.12500000000000003

Дана матрица А

In [93]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

Найдите обратную матрицу к матрице А

In [94]:
Ainv = np.linalg.inv(A)

Ainv[1][0]


0.375

Дана система векторов:

In [95]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

Найдите ранг системы векторов v1, v2, v3, v4.

In [96]:
sys = np.array([v1, v2, v3, v4])
np.linalg.matrix_rank(sys)

4

In [97]:
np.linalg.det(sys)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
(sys@sys.T)[0][3]

In [ ]:
round(np.linalg.det((sys@sys.T)))

In [ ]:
np.linalg.matrix_rank(np.linalg.det((sys@sys.T)))

In [ ]:
round(np.linalg.inv(sys@sys.T)[2][0], 3)

In [ ]:
A = np.array([[4,7],[5,10]])

B = np.array([[4,7,20],[5,10,30]])

np.linalg.matrix_rank(B)